import type {
  AnalysisInput,
  AvailabilityItem,
  HeadToHeadItem,
  MatchSummary,
  TeamSummary,
} from "./sports.types.js";

type TeamSeed = Omit<TeamSummary, "id" | "providerId"> & { id: string };

const teams: Record<string, TeamSeed> = {
  tigres: {
    id: "demo-tigres",
    name: "Tigres UANL",
    shortName: "TIG",
    stadium: "Estadio Universitario",
    city: "San Nicolás de los Garza",
    latitude: 25.7226,
    longitude: -100.311,
    position: 3,
    points: 6,
    matchesPlayed: 5,
    form: ["W", "D", "W", "W", "L"],
    formLabel: "3V · 1E · 1D",
    goalsForAverage: 1.8,
    goalsAgainstAverage: 0.8,
    homeAwayStrength: 0.72,
    unavailablePlayers: 1,
  },
  santos: {
    id: "demo-santos",
    name: "Santos Laguna",
    shortName: "SAN",
    stadium: "Estadio Corona",
    city: "Torreón",
    latitude: 25.6288,
    longitude: -103.3795,
    position: 12,
    points: 3,
    matchesPlayed: 5,
    form: ["L", "W", "D", "L", "W"],
    formLabel: "2V · 1E · 2D",
    goalsForAverage: 1.2,
    goalsAgainstAverage: 1.6,
    homeAwayStrength: 0.61,
    unavailablePlayers: 2,
  },
  america: {
    id: "demo-america",
    name: "Club América",
    shortName: "AME",
    stadium: "Estadio Ciudad de los Deportes",
    city: "Ciudad de México",
    latitude: 19.3832,
    longitude: -99.1781,
    position: 2,
    points: 7,
    matchesPlayed: 5,
    form: ["W", "W", "D", "W", "W"],
    formLabel: "4V · 1E · 0D",
    goalsForAverage: 2,
    goalsAgainstAverage: 0.8,
    homeAwayStrength: 0.8,
    unavailablePlayers: 1,
  },
  toluca: {
    id: "demo-toluca",
    name: "Toluca",
    shortName: "TOL",
    stadium: "Estadio Nemesio Díez",
    city: "Toluca",
    latitude: 19.2871,
    longitude: -99.6663,
    position: 1,
    points: 9,
    matchesPlayed: 5,
    form: ["W", "W", "W", "D", "W"],
    formLabel: "4V · 1E · 0D",
    goalsForAverage: 2.2,
    goalsAgainstAverage: 0.9,
    homeAwayStrength: 0.76,
    unavailablePlayers: 0,
  },
  monterrey: {
    id: "demo-monterrey",
    name: "Monterrey",
    shortName: "MTY",
    stadium: "Estadio BBVA",
    city: "Guadalupe",
    latitude: 25.6691,
    longitude: -100.2443,
    position: 5,
    points: 5,
    matchesPlayed: 5,
    form: ["D", "W", "W", "L", "D"],
    formLabel: "2V · 2E · 1D",
    goalsForAverage: 1.6,
    goalsAgainstAverage: 1.1,
    homeAwayStrength: 0.74,
    unavailablePlayers: 1,
  },
  pumas: {
    id: "demo-pumas",
    name: "Pumas UNAM",
    shortName: "PUM",
    stadium: "Estadio Olímpico Universitario",
    city: "Ciudad de México",
    latitude: 19.332,
    longitude: -99.1922,
    position: 7,
    points: 4,
    matchesPlayed: 5,
    form: ["W", "L", "D", "W", "L"],
    formLabel: "2V · 1E · 2D",
    goalsForAverage: 1.4,
    goalsAgainstAverage: 1.3,
    homeAwayStrength: 0.65,
    unavailablePlayers: 2,
  },
  cruzazul: {
    id: "demo-cruz-azul",
    name: "Cruz Azul",
    shortName: "CAZ",
    stadium: "Estadio Olímpico Universitario",
    city: "Ciudad de México",
    latitude: 19.332,
    longitude: -99.1922,
    position: 4,
    points: 6,
    matchesPlayed: 5,
    form: ["W", "D", "W", "L", "W"],
    formLabel: "3V · 1E · 1D",
    goalsForAverage: 1.7,
    goalsAgainstAverage: 1,
    homeAwayStrength: 0.69,
    unavailablePlayers: 0,
  },
  chivas: {
    id: "demo-chivas",
    name: "Guadalajara",
    shortName: "GDL",
    stadium: "Estadio Akron",
    city: "Zapopan",
    latitude: 20.6818,
    longitude: -103.462,
    position: 8,
    points: 4,
    matchesPlayed: 5,
    form: ["L", "W", "D", "D", "W"],
    formLabel: "2V · 2E · 1D",
    goalsForAverage: 1.3,
    goalsAgainstAverage: 1.2,
    homeAwayStrength: 0.67,
    unavailablePlayers: 1,
  },
};

function match(
  id: string,
  homeKey: string,
  awayKey: string,
  startsAt: string,
  matchday: string,
): MatchSummary {
  const home = teams[homeKey];
  const away = teams[awayKey];
  return {
    id,
    startsAt,
    matchday,
    venue: home.stadium ?? "Por confirmar",
    status: "scheduled",
    home: { ...home },
    away: { ...away },
    sources: ["demo"],
    dataFreshness: "Datos demostrativos",
  };
}

export const demoMatches: MatchSummary[] = [
  match(
    "demo-santos-tigres",
    "santos",
    "tigres",
    "2026-07-24T21:00:00-06:00",
    "Jornada 3",
  ),
  match(
    "demo-america-toluca",
    "america",
    "toluca",
    "2026-07-25T19:00:00-06:00",
    "Jornada 3",
  ),
  match(
    "demo-monterrey-pumas",
    "monterrey",
    "pumas",
    "2026-07-25T21:05:00-06:00",
    "Jornada 3",
  ),
  match(
    "demo-cruz-azul-chivas",
    "cruzazul",
    "chivas",
    "2026-07-26T18:00:00-06:00",
    "Jornada 3",
  ),
];

const availability: Record<string, AvailabilityItem[]> = {
  "demo-santos-tigres": [
    {
      teamId: "demo-santos",
      playerName: "Defensa titular",
      status: "doubtful",
      reason: "Molestia muscular",
      source: "demo",
    },
    {
      teamId: "demo-santos",
      playerName: "Mediocampista",
      status: "suspended",
      reason: "Acumulación de tarjetas",
      source: "demo",
    },
    {
      teamId: "demo-tigres",
      playerName: "Extremo",
      status: "injured",
      reason: "Lesión de tobillo",
      source: "demo",
    },
  ],
  "demo-america-toluca": [
    {
      teamId: "demo-america",
      playerName: "Lateral",
      status: "doubtful",
      reason: "Carga muscular",
      source: "demo",
    },
  ],
};

const h2h: Record<string, HeadToHeadItem[]> = {
  "demo-santos-tigres": [
    {
      date: "2026-02-08",
      home: "Tigres UANL",
      away: "Santos Laguna",
      homeScore: 2,
      awayScore: 1,
    },
    {
      date: "2025-08-31",
      home: "Santos Laguna",
      away: "Tigres UANL",
      homeScore: 0,
      awayScore: 1,
    },
    {
      date: "2025-03-15",
      home: "Tigres UANL",
      away: "Santos Laguna",
      homeScore: 1,
      awayScore: 1,
    },
    {
      date: "2024-09-22",
      home: "Santos Laguna",
      away: "Tigres UANL",
      homeScore: 2,
      awayScore: 2,
    },
    {
      date: "2024-02-11",
      home: "Tigres UANL",
      away: "Santos Laguna",
      homeScore: 3,
      awayScore: 0,
    },
  ],
  "demo-america-toluca": [
    {
      date: "2026-03-01",
      home: "Toluca",
      away: "Club América",
      homeScore: 2,
      awayScore: 2,
    },
    {
      date: "2025-11-08",
      home: "Club América",
      away: "Toluca",
      homeScore: 1,
      awayScore: 2,
    },
    {
      date: "2025-05-24",
      home: "Toluca",
      away: "Club América",
      homeScore: 0,
      awayScore: 0,
    },
  ],
};

export function demoContext(id: string): AnalysisInput {
  const selected = demoMatches.find((item) => item.id === id) ?? demoMatches[0];
  return {
    match: selected,
    availability: availability[selected.id] ?? [],
    headToHead: h2h[selected.id] ?? [],
    restDays: { home: 6, away: 6 },
    coverage: {
      standings: true,
      form: true,
      availability: true,
      headToHead: (h2h[selected.id] ?? []).length > 0,
      weather: Boolean(selected.weather),
    },
  };
}
